version: '3.7'

networks:
  mp-network:

services:

  my-sql:
    container_name: mysql-server
    image: mysql/mysql-server:8.0.13
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cred_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    expose:
      - 3306
    networks:
      - mp-network
    tty:
      true

  config-server:
    container_name: config-server
    build:
      context: ./config
      dockerfile: Dockerfile
    image: config-server:latest
    expose:
      - 8888
    networks:
      - mp-network
    tty:
      true

  discovery-server:
    container_name: discovery-server
    build:
      context: ./discovery
      dockerfile: Dockerfile
    image: discovery-server:latest
    expose:
      - 8761
    networks:
      - mp-network
    tty:
      true
    depends_on:
      - config-server

  gateway:
    container_name: gateway-server
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: gateway-server:latest
    expose:
      - 8100
    ports:
      - target: 8100
        published: 8100
        protocol: tcp
        mode: host
    networks:
      - mp-network
    tty:
      true
    depends_on:
      - config-server
      - discovery-server

  auth-server:
    container_name: auth-server
    build:
      context: ./auth
      dockerfile: Dockerfile
    image: auth-server:latest
    expose:
      - 8200
    networks:
      - mp-network
    tty:
      true
    depends_on:
      - config-server
      - discovery-server
      - my-sql
