version: '3.7'

networks:
  mp-network:

services:

  my-sql:
    container_name: mysql-server
    build:
      context: .
      dockerfile: Dockerfile-mysql-server
    image: mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - mp-network

  config-server:
    container_name: config-server
    build:
      context: .
      dockerfile: Dockerfile-config-server
    image: config-server:latest
    expose:
      - 8888
    ports:
      - 8888:8888
    networks:
      - mp-network

  discovery-server:
    container_name: discovery-server
    build:
      context: .
      dockerfile: Dockerfile-discovery-server
    image: discovery-server:latest
    expose:
      - 8761
    ports:
      - 8761:8761
    networks:
      - mp-network
    depends_on:
      - config-server

  gateway:
    container_name: gateway-server
    build:
      context: .
      dockerfile: Dockerfile-gateway-server
    image: gateway-server:latest
    expose:
      - 8100
    ports:
      - 8100:8100
    networks:
      - mp-network
    depends_on:
      - config-server
      - discovery-server

  auth-server:
    container_name: auth-server
    build:
      context: .
      dockerfile: Dockerfile-auth-server
    image: auth-server:latest
    expose:
      - 8200
    ports:
      - 8200:8200
    networks:
      - mp-network
    depends_on:
      - config-server
      - discovery-server
      - my-sql
